version: "3.7"
services:
  mongodb:
    image: mongo:5.0
    expose:
      - "27017"
    networks:
      - grpc_network

  database-microservice-server:
    build: app/
    ports:
      - 50051:50051
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    networks:
      - grpc_network

networks:
  grpc_network:
    name: grpc_network
